sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install kotlin-native
  - sudo snap install kotlin
install:
  - ./gradlew -b jvm-build.gradle tests
  - ./gradlew -b native-build.gradle tests